const REQUEST_TIMELINE_JSON = 'REQUEST_TIMELINE_JSON';
const RECEIVE_TIMELINE_JSON = 'RECEIVE_TIMELINE_JSON';
const REQUEST_TREND_JSON = 'REQUEST_TREND_JSON';
const RECEIVE_TREND_JSON = 'RECEIVE_TREND_JSON';
const RECEIVE_SEARCH_JSON = 'RECEIVE_SEARCH_JSON';

export default {
  REQUEST_TIMELINE_JSON,
  RECEIVE_TIMELINE_JSON,
  REQUEST_TREND_JSON,
  RECEIVE_TREND_JSON,
  RECEIVE_SEARCH_JSON
}
